# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'HourCalculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HourCalculator
pod 'SwipeableTabBarController'

  target 'HourCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HourCalculatorUITests' do
    # Pods for testing
  end

end
